#!/bin/bash

# Usage: ./bump-version 2.8.awesome

NEW_VERSION="$1"
DIRECTORIES="
             bioclipse.balloon/plugins/net.bioclipse.*
             bioclipse.balloon/features/net.bioclipse.balloon_feature
             bioclipse.cheminformatics/plugins/net.bioclipse.*
             bioclipse.cheminformatics/features/net.bioclipse.cdk_feature
             bioclipse.cheminformatics/features/net.bioclipse.chemoinformatics_feature
             bioclipse.cheminformatics/features/net.bioclipse.cdk_feature
             bioclipse.statistics/plugins/net.bioclipse.*
             bioclipse.statistics/features/net.bioclipse.statistics_feature
             bioclipse.rdf/plugins/net.bioclipse.*
             bioclipse.rdf/features/net.bioclipse.cheminformatics.rdf_feature
             bioclipse.rdf/features/net.bioclipse.pellet_feature
             bioclipse.rdf/features/net.bioclipse.rdf.ui_feature
             bioclipse.rdf/features/net.bioclipse.rdf_feature
             bioclipse.core/plugins/net.bioclipse.*
             bioclipse.core/features/net.bioclipse.core_feature
             bioclipse.core/features/net.bioclipse.platform_feature
             bioclipse.social/plugins/net.bioclipse.*
             bioclipse.social/features/net.bioclipse.social_feature
             bioclipse.qsar/plugins/net.bioclipse.qsar*
             bioclipse.qsar/plugins/net.bioclipse.cdk*
             bioclipse.qsar/features/net.bioclipse.qsar.xmpp_feature
             bioclipse.qsar/features/net.bioclipse.qsar_feature
             bioclipse.ds/plugins/net.bioclipse.*
             bioclipse.ds/features/net.bioclipse.*
             bioclipse.experimental/plugins/net.bioclipse.*
             bioclipse.experimental/features/net.bioclipse.*
             "
for file in `find $DIRECTORIES -name MANIFEST.MF -or -name feature.xml`; do
    perl -i -lpe '
        BEGIN { $l = 0 }
        if (/^Bundle-Version:/) {
            $_ = "Bundle-Version: '$NEW_VERSION'"
        }
        elsif (/^(\s+)version="/ && !$l++) {
            $_ = $1 . q[version="'$NEW_VERSION'"]
        }' $file
done
perl -i -lpe '
    s/^(\<product.*?version=)".*?"/$1"'$NEW_VERSION'"/; 
    s/(-Declipse.buildId=\&quot).*?(\&quot;)/$1;'$NEW_VERSION'$2/;
' bioclipse.core/features/net.bioclipse.platform_feature/bioclipse.product

echo 0=$NEW_VERSION > bioclipse.core/plugins/net.bioclipse.ui/about.mappings
